from __future__ import annotations

import re

MISSING_API_KEY = "MISSING_API_KEY"
MISSING_SMTP_CONFIG = "MISSING_SMTP_CONFIG"
MISSING_CITY = "MISSING_CITY"
MISSING_ORIGIN = "MISSING_ORIGIN"
MISSING_DESTINATION = "MISSING_DESTINATION"
MISSING_TO = "MISSING_TO"
MISSING_SUBJECT = "MISSING_SUBJECT"
MISSING_BODY = "MISSING_BODY"
INVALID_EMAIL = "INVALID_EMAIL"
FORBIDDEN_RECIPIENT = "FORBIDDEN_RECIPIENT"
INJECTION_BLOCKED = "INJECTION_BLOCKED"
CONTENT_TOO_LONG = "CONTENT_TOO_LONG"
EMAIL_CANCELLED = "EMAIL_CANCELLED"
INVALID_WHEN = "INVALID_WHEN"
INVALID_MODE = "INVALID_MODE"
FORECAST_NOT_FOUND = "FORECAST_NOT_FOUND"
CITY_NOT_FOUND = "CITY_NOT_FOUND"
PLACE_NOT_FOUND = "PLACE_NOT_FOUND"
AMAP_ERROR = "AMAP_ERROR"
HTTP_STATUS = "HTTP_STATUS"
NETWORK = "NETWORK"
SMTP_AUTH = "SMTP_AUTH"
SMTP_CONNECT = "SMTP_CONNECT"
SMTP_SEND = "SMTP_SEND"
SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
SCRIPT_LOAD = "SCRIPT_LOAD"
NO_ENTRYPOINT = "NO_ENTRYPOINT"
DEFERRED_SKILL = "DEFERRED_SKILL"
FORBIDDEN_SKILL = "FORBIDDEN_SKILL"
DUPLICATE = "DUPLICATE"
BUDGET = "BUDGET"
TOKEN_BUDGET = "TOKEN_BUDGET"

_CODE_RE = re.compile(r"^\[([A-Z][A-Z0-9_]{1,40})\]")


def skill_error(code: str, message: str) -> str:
    return f"[{code}] {message}"


def skill_error_code(text: str) -> str | None:
    match = _CODE_RE.match((text or "").lstrip())
    return match.group(1) if match else None
